### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Timemon** [VikeStep/sprinkles_for_vanilla#11]
Option to disable the use of ender pearls. This would be cool as it would disable vanilla 'teleportation'  it doesn't seem to be available in any forge mods and would fit perfectly with Sprinkles For Vanilla.

**Comment by VikeStep** [comment]
It was pretty easy so I just added it for you. Will be in the next release but I have some more features to add before then

**Comment by Timemon** [comment]
Thankyou
