### ISSUE TITLE
Client only option

### ISSUE THREAD

**Issue by hilburn** [VikeStep/sprinkles_for_vanilla#12]
I'd really like it if there was a "client only" version which would only disable the potion effects/do other client side stuff

**Comment by VikeStep** [comment]
What I have done is make it so that non-client features aren't activated if the mod is not on the server. I think I have got it working, just gonna do some quick testing to make sure it works and I'll commit it

**Comment by hilburn** [comment]
Awesome - looking forward to it

**Comment by VikeStep** [comment]
I want to test this a bit more before releasing it, but it works ok so far so I'm closing the issue. I'll push a new release tomorrow once I'm happy that it works
