### ISSUE TITLE
Hurt "effect" still happens from disabled damage sources

### ISSUE THREAD

**Issue by KaiserYoshi** [VikeStep/sprinkles_for_vanilla#14]
Even though a damage source is disabled, it still triggers the sound, screen shake, and knockback, which can be extremely annoying when doing something like swimming across a lake of lava.

This also applies to non-players - a monster in contact with a disabled damage source will still play the hurt sound and animation, which can mislead players about a monster's health.

**Comment by VikeStep** [comment]
This will be added in 1.0.7
