### ISSUE TITLE
Crash with v1.1.0

### ISSUE THREAD

**Issue by maxlowry123** [VikeStep/sprinkles_for_vanilla#15]
There is a crash on startup. Based on the log it is an issue with Morph/Morph Additions (http://bit.ly/MorphAdd). If it was just Morph Additions I would not have a problem removing it but I don't want to remove Morph. It only happens when I add this mod. 
With MorphAdditions: http://paste.ubuntu.com/9755716/
With just Morph: http://paste.ubuntu.com/9755747/
If you want I can also add a list of mods I have.

**Comment by VikeStep** [comment]
If you remove Morph does the crash no longer occur?

**Comment by maxlowry123** [comment]
No, it still crashes this time with SpecialMobs.
http://paste.ubuntu.com/9755871/

**Comment by VikeStep** [comment]
does it occur if you remove specialmobs? I think  its just a coincidence that these mods are crashing with it. i doubt they are the actual conflicting mod.

**Comment by maxlowry123** [comment]
Now it looks like it saying OpenBlocks.
http://paste.ubuntu.com/9755945/

**Comment by maxlowry123** [comment]
I just removed OpenBlocks and with all of the other mods still removed it starts.

**Comment by VikeStep** [comment]
OK its midnight where I am so I'll look into it tomorrow when I wake up.

**Comment by maxlowry123** [comment]
Ok that is fine, thank you for looking at this, I would like to be able to use this mod and still use the other ones.

**Comment by VikeStep** [comment]
I have put OpenBlocks, Morph, and Morph Additions in with sprinkles_for_vanilla and no such crash occurs. Are you able to send me your config?

**Comment by Gorgok** [comment]
I believe that crash is one i just came to post about. Its a conflict with Code Chicken Core, if you have environmentallyFriendlyCreepers=true in its configs. This happens even with sprinkles' config set to not do anything for mob griefing settings. Change it to false (default) and its fine, can use sprinkles' mob griefing settings instead.

**Comment by VikeStep** [comment]
Thank you, I think I know how to fix it. :)

**Comment by VikeStep** [comment]
Can you try downloading this (both of you) and see if this resolves the issue?
https://mega.co.nz/#!f5EllBaJ!Gb5K1E8RrB3en009GfZm4kqXjBCZ_r0QBPB_bRgo93s

If it works, I'll push it as a proper release

**Comment by maxlowry123** [comment]
Thank you, that works, I did not even think to try that.

**Comment by VikeStep** [comment]
Thanks for helping out, it's now a proper release on curseforge
