### ISSUE TITLE
Change "doEnderPearlsTeleport" to disable the pearls being thrown instead of the actual teleportation

### ISSUE THREAD

**Issue by KaiserYoshi** [VikeStep/sprinkles_for_vanilla#19]
As it currently is, using this option to disable ender pearls also prevents endermen from teleporting entirely. It seems like any entity that uses this teleportation routine is also affected by this, which is not cool. Changing the config to prevent ender pearls from being thrown would achieve the desired end without affecting other entities, and would also remove the right-click as the "flush valuable ender pearl down toilet" button that is far too easy to hit by accident.

**Comment by VikeStep** [comment]
Hmm, I didn't think of other things also firing this event, I can add this in the next update (which won't be for a few days). Sorry for the inconvenience
