### ISSUE TITLE
sleep settings overriding an existing periodic ban on sleep.

### ISSUE THREAD

**Issue by Dulciphi** [VikeStep/sprinkles_for_vanilla#21]
That title's a little misleading, sorry. Improvements would be appreciated.

I was using Sprinkles's sleep settings to increase the minimum safe distance to monsters. It worked exactly as desired, preventing players from just plopping down beds in the open, within sight of hostiles. However, I'm also using [Random Things](http://minecraft.curseforge.com/mc-mods/59816-random-things) by Lumien. One of the features of Random Things is a periodic Blood Moon, during which no one can sleep. The addition of the sleep settings in Sprinkles allowed players to sleep during Blood Moons. That is, it overrode the existing Blood Moon ban on sleep.

I understand that my usage of this sleep setting isn't exactly standard or necessarily intended, but it was very useful and irreplaceable. I'm therefore wondering if it might be possible to add some kind of "if" statement check, before checking to see if a player can sleep. 

Thank you.

**Comment by VikeStep** [comment]
I am aware of this and have written a fix, but currently I'm doing a massive refactor on the mod so when that is done I will push the update live. Sorry for the inconvenience, but for now you should disable the sleep overhaul in the configs if you don't want this to happen

**Comment by Dulciphi** [comment]
Done, and thank you. Good luck with the refactor. I look forward to it.
