### ISSUE TITLE
ExplosionHandler NullPointerException while using QuiverBow ERA

### ISSUE THREAD

**Issue by Choonster** [VikeStep/sprinkles_for_vanilla#26]
sprinkles_for_vanilla: 1.2.0beta
QuiverBow: b100
Crash Report: https://gist.github.com/Choonster/156f52764bf6eca94496

Crash occurs shortly after using the Ender Rail Accelerator from QuiverBow (I believe it's meant to charge up and then fire an exploding projectile).

I'm not entirely sure if this is an issue on your end or on QuiverBow's.

**Comment by Mattsingen** [comment]
We have another almost the same crash but in combination with Blood Magic.
http://openeye.openmods.info/crashes/b8cb9f3ea0e4c8c653bacd02ba2f68a0

I'm not the one that got the crash, it was reported on the RR3 forum.

**Comment by VikeStep** [comment]
Fixed in next version
