### ISSUE TITLE
Crash java.lang.NullPointerException: Exception while updating neighbours

### ISSUE THREAD

**Issue by Staegrin** [VikeStep/sprinkles_for_vanilla#29]
Just digging up some dirt when my game crashes. 
crashlog:
http://pastebin.com/PJPwZWav
fml-client-latest:
https://gist.github.com/Staegrin/71ad38dd4640f5198851

**Comment by VikeStep** [comment]
Can you test without CoFHCore? It does some changes to liquids that conflict with my mod.

If it doesn't happen again without CoFHCore let me know.

**Comment by Staegrin** [comment]
Happens without any cofh mod including core.
Only your mod NEI and various chickenbones mods along with veinminer. Happened again when shovelling dirt for some reason.
crashlog:
http://pastebin.com/c0iPxPjY
fml-client-latest:
https://gist.github.com/Staegrin/ecd6de9366ffd5773af4

**Comment by VikeStep** [comment]
1.2.1 is now on curseforge with the fix http://minecraft.curseforge.com/mc-mods/226309-sprinkles_for_vanilla/files/2238481
