### ISSUE TITLE
Crash with Draconic Evolution Resurrection Ritual

### ISSUE THREAD

**Issue by brandon3055** [VikeStep/sprinkles_for_vanilla#31]
Reposting a crash that was reported to me when someone tries to do my resurrection ritual with your mod installed.

I tried recreating this crash but i was unable to get the mod to work properly in my dev environment. It loaded but kept crashing when i tried to login to a world. It threw a bunch of different errors that dont really make sense and i dont have time to figure them out at the moment.

Here is the original crash report: http://pastebin.com/Chq3juSH
Original issue: https://github.com/brandon3055/Draconic-Evolution/issues/94  

According to the report the crash originates here:
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/tileentities/multiblocktiles/TileEnderResurrection.java#L72

But all thats doing is creating an explosion so im pretty sure the problem is on your end.

**Comment by VikeStep** [comment]
This was fixed in 1.2.0beta2, and I'm guessing this is a RR pack. I've spoken to RR devs and they are updating the mod next pack update.

**Comment by VikeStep** [comment]
If you were curious, I was trying to get the name of the exploder from the EntityList and the entity did not have a name there

**Comment by brandon3055** [comment]
Ok and thanks for the quick reply! Its always nice when its not my mods fault lol
