### ISSUE TITLE
ExplosionHandler NullPointerException when explosion.exploder is null

### ISSUE THREAD

**Issue by Choonster** [VikeStep/sprinkles_for_vanilla#32]
sprinkles_for_vanilla: 1.2.2 (offending code is still in 1.2.6)
FML log: http://paste.atlauncher.com/view/ea8fd3f3 (crash report starts on line 408)

When `explosion.exploder` is `null` in `ExplosionHandler#onExplosionStart` ([line 59](https://github.com/VikeStep/sprinkles_for_vanilla/blob/dbc0a26b6acca3ecd2d85c3aabc024a1fa525c58/src/main/java/io/github/vikestep/sprinklesforvanilla/common/handlers/WorldHandlers.java#L59)) with `global -> explosions -> explosionLogging` set to `true`, `EntityList.getEntityString` throws a `NullPointerException`.

Originally reported [here](http://www.resonant-rise.com/topic/6278-mc-boots-me-to-title-screen-when-trying-to-play/?p=42866).

**Comment by VikeStep** [comment]
I'll upload this update shortly. May I suggest disabling explosion logging by default. When you get to things like the dragon or wither it will become incredibly spammy. The only reason I included the explosion logging was for if you wished to add your own explosion rules and wished to know the name of the explosion to use.

**Comment by Choonster** [comment]
Thanks for the quick response.

Explosion logging was disabled by default in the pack, so the user must have enabled it themselves.

**Comment by VikeStep** [comment]
What could've also happened is that the server had it enabled. My mod has config syncing so it will use the server's values when possible.
