### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by SkeletonPunk** [VikeStep/sprinkles_for_vanilla#33]
http://pastebin.com/CHyQiQbb

**Comment by VikeStep** [comment]
Can you pastebin your config for me? I just need to see what was set and why it is breaking

**Comment by SkeletonPunk** [comment]
http://pastebin.com/emZRgXeA

**Comment by VikeStep** [comment]
Turns out I forgot to add in the functionality which allows you to comment things out. Will fix in a moment, for now I suggest removing that comment. I won't push a mod update solely for this fix but it will be in the next build
