### ISSUE TITLE
Feature Request - Forced Dimension Spawning

### ISSUE THREAD

**Issue by GustoniaEagle** [VikeStep/sprinkles_for_vanilla#36]
Hey VikeStep,

  Can you please add a config option to make the player respawn in the dimension they died in, rather than in the overworld?
  ie. When a player currently dies in the Nether, they respawn in the Overworld. Config option would make them respawn in the Nether.

  Thanks!

**Comment by VikeStep** [comment]
This is already a feature. I can't check its name right  now but it should be in the spawning category

**Comment by GustoniaEagle** [comment]
There's one that allows you to set an x, y and z, but is that certain to not just drop the player in a hole? Especially with the End, since the obsidian platform location varies.
