### ISSUE TITLE
Request: Colored Lights support

### ISSUE THREAD

**Issue by xeronut** [VikeStep/sprinkles_for_vanilla#38]
Hello!  I read in your 1.5.0 changelog that you added "Config option to set the light value of any block from any mod".  This is already pretty cool, but would it be possible to add support for the Colored Light Mod?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and

I would not know how difficult this actually is, but several mods (Botania, Reika's mods, BluePower, Project: Red, Rainbow Liquids, several others) have added support for it over the last few months.  Being able to assign a color to just about anything would be.. amazing.  Thanks for your time!

**Comment by VikeStep** [comment]
As much as it is a cool idea, it is out of scope of the mod I'm afraid, this feature is specifically for a mod, I only add features for vanilla but sometimes extend it generally to any mod.

**Comment by xeronut** [comment]
Understood - thank you for the reply!  :)
