### ISSUE TITLE
crash 'particleSpawnedFromEntity'

### ISSUE THREAD

**Issue by Thorton101** [VikeStep/sprinkles_for_vanilla#42]
Hello VikeStep,

I put a testpack for minecraft version 1.8.9 together and used your mod to turn off the annoying
landscape-destroying creeper explosions.
Started a new world and I ran into a poison ivy from biomeso'plenty and my game crashed.

Here is the crashreport I uploaded on pastebin:
[http://pastebin.com/EVa7Dth1]

Hope your the correct receiver for that crash.

Best regards Thorton101

**Comment by VikeStep** [comment]
I can confirm this is my issue, currently at work so I will fix it when I get home
